CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) NOT NULL,
    name  VARCHAR(50) NOT NULL,
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    available   BOOLEAN,
    owner_id    BIGINT      NOT NULL
        CONSTRAINT items_owner_id_fk
            REFERENCES users (id)
            ON DELETE CASCADE,
    request_id  BIGINT
);

create table if not exists booking
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp without time zone,
    end_date   timestamp without time zone,
    item_id    bigint      not null
        constraint booking_item_id
            references items (id)
            on delete cascade,
    booker_id  bigint      not null
        constraint booking_user_id
            references users (id)
            on delete cascade,
    status     varchar(10) not null
);

create table if not exists comments
(
    id        bigserial
        constraint comments_pk
            primary key,
    text      varchar(1024)               not null,
    item_id   bigint                      not null
        constraint comments_item_id
            references items
            on update cascade on delete cascade,
    author_id bigint                      not null
        constraint comments_author_id
            references users
            on update cascade on delete cascade,
    created   timestamp without time zone not null
);